all:
	g++ -c -std=c++11 Shape.cpp Rectangle.cpp Circle.cpp Triangle.cpp Polygon.cpp PolygonDyn.cpp PolygonVect.cpp ComposedShape.cpp Main.cpp 
	g++ -o Shape.o Rectangle.o Circle.o Main.o Triangle.o Polygon.o PolygonDyn.o PolygonVect.o ComposedShape.o -o ./exe
run:
	./exe

clean:
	rm *.o exe
	clear

