all:
	g++ -std=c++11 -c Rectangle.cpp Triangle.cpp Circle.cpp Polygon.cpp Polyline.cpp ComposedShape.cpp Main.cpp 
	g++ Rectangle.o Triangle.o Circle.o Polygon.o Polyline.o ComposedShape.o Main.o -o exe

run:
	./exe

clean:
	rm *.o exe
	clear

